// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzkybdlm7EPt9OT9jGhb_p6-5f2L4RMJI',
    appId: '1:292898318166:web:008dae90b5b42cc76918f7',
    messagingSenderId: '292898318166',
    projectId: 'bookstore-app-adba9',
    authDomain: 'bookstore-app-adba9.firebaseapp.com',
    storageBucket: 'bookstore-app-adba9.appspot.com',
    measurementId: 'G-DECTECFGWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4uHE2s3FqOnx77eSLOEfO7fc4cDABluA',
    appId: '1:292898318166:android:903f85d338a034696918f7',
    messagingSenderId: '292898318166',
    projectId: 'bookstore-app-adba9',
    storageBucket: 'bookstore-app-adba9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaI9cRTZZeT44S6-3ymOKsbUBS-gjf7Es',
    appId: '1:292898318166:ios:de55e1d4d8a609536918f7',
    messagingSenderId: '292898318166',
    projectId: 'bookstore-app-adba9',
    storageBucket: 'bookstore-app-adba9.appspot.com',
    iosClientId: '292898318166-2rm3hk8db9cjm9t7v6iojqvlqpvqtsi0.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaI9cRTZZeT44S6-3ymOKsbUBS-gjf7Es',
    appId: '1:292898318166:ios:4d67e573d90840e26918f7',
    messagingSenderId: '292898318166',
    projectId: 'bookstore-app-adba9',
    storageBucket: 'bookstore-app-adba9.appspot.com',
    iosClientId: '292898318166-afq49fngfgoi83epmbvng7kprbh3ekob.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookstore.RunnerTests',
  );
}
